version: '3.8'

services:

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
    restart: always
    environment:
      POSTGRES_DATABASE_URL: "postgresql://postgres:password@db:5432/postgres"
  caddy:
    image: caddy:2.4.6
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data:
  postgres_data: